spring:
  # flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    #baseline-version: 1.0.0
    baseline-description: Initial
    locations:
      - classpath:/db/migration
  # dev
  devtools:
    livereload:
      enabled: true